Repository Galaxypedia-Wiki/Galaxypedia, pull requests merged in 2024-12, with the labels that each got.

#36 Fix the footer containing a printf statement
  layouts/partials/github-user.html
Labels: site:partials

#37 Add notices
  content/wiki/deity/index.md
  hugo_stats.json
  layouts/partials/notice.html
  layouts/shortcodes/notices/advancedShip.html
  layouts/shortcodes/notices/editQuality.html
  layouts/shortcodes/notices/limitedShip.html
  layouts/shortcodes/notices/notice.html
  layouts/shortcodes/notices/superCapitalShip.html
  layouts/shortcodes/notices/underConstruction.html
Labels: site:shortcodes, site:partials

#39 Add archetypes
  archetypes/default.md
  archetypes/wiki/assets/.gitkeep
  archetypes/wiki/index.md
Labels: site:platform, site:content

#43 Switch to yaml for hugo configuration and add a robots.txt
  hugo.toml
  hugo.yaml
  layouts/robots.txt
Labels: site:platform

#44 Only load Sentry if the site is built in CI
  layouts/_default/baseof.html
Labels: site:platform

#46 Add CODEOWNERS
  .github/CODEOWNERS
Labels: site:tooling, size/XS

#45 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: site:tooling, size/M

#49 Switch to Cloudflare Pages
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/hugo-deploy.yml
  .github/workflows/pull-request.yml
Labels: site:tooling, size/L

#53 Add a codefactor badge to the github readme
  README.md
Labels: site:tooling, size/XS

#52 Fix BaseURL in PR Deployments
  .github/workflows/build.yml
Labels: site:tooling, size/S

#57 Remove empty block in shipinfobox shortcode
  layouts/shortcodes/shipInfobox.html
Labels: site:shortcodes, size/XS

#60 Fix a mistake in the build workflow
  .github/workflows/build.yml
  .github/workflows/pull-request.yml
Labels: site:platform, site:tooling, size/XS

#65 improve autolabeler configuration
  .github/labeler.yml
Labels: priority:high, site:tooling, size/M

#64 Make borders black for now
  content/_index.md
Labels: site:platform, size/S

#66 Fix ci baseurl again
  .github/workflows/build.yml
Labels: site:tooling, size/S

#70 Unify pagefind code and disable subresults
  layouts/_default/baseof.html
  layouts/_default/single.html
  layouts/index.html
Labels: site:platform, size/S

#71 Fix main page having a long ass embed description
  content/_index.md
Labels: size/XS

#72 fix the title of the main page
  layouts/_default/baseof.html
Labels: site:platform, size/XS

#73 refactor baseof
  layouts/_default/baseof.html
  layouts/partials/notice.html
  layouts/partials/site/footer.html
  layouts/partials/site/head.html
  layouts/partials/site/kofi.html
  layouts/partials/site/meta.html
  linkinator.config.json
Labels: site:platform, site:partials, site:tooling, size/L

#76 Make the galaxypedia festive
  .prettierignore
  assets/js/snowstorm-min.js
  content/_index.md
  content/christmas.png
  layouts/partials/site/head.html
Labels: site:platform, site:content, site:partials, site:tooling, size/S
